version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    ports:
      - '5432:5432'
